format = """
[┌──](bold green) $directory$git_branch$git_status
[└─](bold green)$character"""

right_format = """$cmd_duration"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold yellow"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[nodejs]
symbol = " "
detect_files = ["package.json"]

[python]
symbol = " "
detect_files = ["pyproject.toml", "requirements.txt"]

[golang]
symbol = " "
detect_files = ["go.mod"]

[rust]
symbol = " "
detect_files = ["Cargo.toml"]

[dotnet]
symbol = " "
detect_files = ["*.csproj", "*.sln"]
